# Generated by Django 3.0.13 on 2021-03-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default img', upload_to='img/%y'),
        ),
    ]
