# Generated by Django 3.0.13 on 2021-03-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210307_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='static/images/default.png', null=True, upload_to=''),
        ),
    ]
