# Generated by Django 3.0.13 on 2021-03-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210307_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/images/d.png', upload_to='images/'),
        ),
    ]
